/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package aeson-1.5.6.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.5.6.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_aeson */

/* package aeson-pretty-0.8.9 */
#ifndef VERSION_aeson_pretty
#define VERSION_aeson_pretty "0.8.9"
#endif /* VERSION_aeson_pretty */
#ifndef MIN_VERSION_aeson_pretty
#define MIN_VERSION_aeson_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_aeson_pretty */

/* package attoparsec-0.13.2.5 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.13.2.5"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_attoparsec */

/* package attoparsec-binary-0.2 */
#ifndef VERSION_attoparsec_binary
#define VERSION_attoparsec_binary "0.2"
#endif /* VERSION_attoparsec_binary */
#ifndef MIN_VERSION_attoparsec_binary
#define MIN_VERSION_attoparsec_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_attoparsec_binary */

/* package base-4.14.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package conduit-1.3.4.2 */
#ifndef VERSION_conduit
#define VERSION_conduit "1.3.4.2"
#endif /* VERSION_conduit */
#ifndef MIN_VERSION_conduit
#define MIN_VERSION_conduit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_conduit */

/* package conduit-extra-1.3.5 */
#ifndef VERSION_conduit_extra
#define VERSION_conduit_extra "1.3.5"
#endif /* VERSION_conduit_extra */
#ifndef MIN_VERSION_conduit_extra
#define MIN_VERSION_conduit_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_conduit_extra */

/* package cryptonite-0.29 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.29"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */

/* package memory-0.15.0 */
#ifndef VERSION_memory
#define VERSION_memory "0.15.0"
#endif /* VERSION_memory */
#ifndef MIN_VERSION_memory
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_memory */

/* package random-1.2.0 */
#ifndef VERSION_random
#define VERSION_random "1.2.0"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package rio-0.1.21.0 */
#ifndef VERSION_rio
#define VERSION_rio "0.1.21.0"
#endif /* VERSION_rio */
#ifndef MIN_VERSION_rio
#define MIN_VERSION_rio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 21)
#endif /* MIN_VERSION_rio */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package tuple-0.3.0.2 */
#ifndef VERSION_tuple
#define VERSION_tuple "0.3.0.2"
#endif /* VERSION_tuple */
#ifndef MIN_VERSION_tuple
#define MIN_VERSION_tuple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_tuple */

/* package unliftio-0.2.21.0 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.21.0"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 21)
#endif /* MIN_VERSION_unliftio */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* tool gcc-11.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  2 || \
  (major1) == 11 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.8.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "hcryptomotor-0.1.0.0-F9QQQ55wQM5EgxYbUtVWti"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "hcryptomotor-0.1.0.0-F9QQQ55wQM5EgxYbUtVWti"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package aeson-1.5.6.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.5.6.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_aeson */

/* package aeson-pretty-0.8.9 */
#ifndef VERSION_aeson_pretty
#define VERSION_aeson_pretty "0.8.9"
#endif /* VERSION_aeson_pretty */
#ifndef MIN_VERSION_aeson_pretty
#define MIN_VERSION_aeson_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_aeson_pretty */

/* package attoparsec-0.13.2.5 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.13.2.5"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_attoparsec */

/* package attoparsec-binary-0.2 */
#ifndef VERSION_attoparsec_binary
#define VERSION_attoparsec_binary "0.2"
#endif /* VERSION_attoparsec_binary */
#ifndef MIN_VERSION_attoparsec_binary
#define MIN_VERSION_attoparsec_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_attoparsec_binary */

/* package base-4.14.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package conduit-1.3.4.2 */
#ifndef VERSION_conduit
#define VERSION_conduit "1.3.4.2"
#endif /* VERSION_conduit */
#ifndef MIN_VERSION_conduit
#define MIN_VERSION_conduit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_conduit */

/* package conduit-extra-1.3.5 */
#ifndef VERSION_conduit_extra
#define VERSION_conduit_extra "1.3.5"
#endif /* VERSION_conduit_extra */
#ifndef MIN_VERSION_conduit_extra
#define MIN_VERSION_conduit_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_conduit_extra */

/* package cryptonite-0.29 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.29"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package memory-0.15.0 */
#ifndef VERSION_memory
#define VERSION_memory "0.15.0"
#endif /* VERSION_memory */
#ifndef MIN_VERSION_memory
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_memory */

/* package optparse-applicative-0.16.1.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.16.1.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 1)
#endif /* MIN_VERSION_optparse_applicative */

/* package optparse-generic-1.4.7 */
#ifndef VERSION_optparse_generic
#define VERSION_optparse_generic "1.4.7"
#endif /* VERSION_optparse_generic */
#ifndef MIN_VERSION_optparse_generic
#define MIN_VERSION_optparse_generic(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 7)
#endif /* MIN_VERSION_optparse_generic */

/* package process-1.6.13.2 */
#ifndef VERSION_process
#define VERSION_process "1.6.13.2"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 13)
#endif /* MIN_VERSION_process */

/* package random-1.2.0 */
#ifndef VERSION_random
#define VERSION_random "1.2.0"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package rio-0.1.21.0 */
#ifndef VERSION_rio
#define VERSION_rio "0.1.21.0"
#endif /* VERSION_rio */
#ifndef MIN_VERSION_rio
#define MIN_VERSION_rio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 21)
#endif /* MIN_VERSION_rio */

/* package system-filepath-0.4.14 */
#ifndef VERSION_system_filepath
#define VERSION_system_filepath "0.4.14"
#endif /* VERSION_system_filepath */
#ifndef MIN_VERSION_system_filepath
#define MIN_VERSION_system_filepath(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 14)
#endif /* MIN_VERSION_system_filepath */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package tuple-0.3.0.2 */
#ifndef VERSION_tuple
#define VERSION_tuple "0.3.0.2"
#endif /* VERSION_tuple */
#ifndef MIN_VERSION_tuple
#define MIN_VERSION_tuple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_tuple */

/* package unliftio-0.2.21.0 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.21.0"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 21)
#endif /* MIN_VERSION_unliftio */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* tool gcc-11.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  2 || \
  (major1) == 11 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.8.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "hcryptomotor-0.1.0.0-96tiUVkj8H6mQp7jj0SCg-hcryptomotor"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package aeson-1.5.6.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.5.6.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_aeson */

/* package aeson-pretty-0.8.9 */
#ifndef VERSION_aeson_pretty
#define VERSION_aeson_pretty "0.8.9"
#endif /* VERSION_aeson_pretty */
#ifndef MIN_VERSION_aeson_pretty
#define MIN_VERSION_aeson_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_aeson_pretty */

/* package attoparsec-0.13.2.5 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.13.2.5"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_attoparsec */

/* package attoparsec-binary-0.2 */
#ifndef VERSION_attoparsec_binary
#define VERSION_attoparsec_binary "0.2"
#endif /* VERSION_attoparsec_binary */
#ifndef MIN_VERSION_attoparsec_binary
#define MIN_VERSION_attoparsec_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_attoparsec_binary */

/* package base-4.14.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package conduit-1.3.4.2 */
#ifndef VERSION_conduit
#define VERSION_conduit "1.3.4.2"
#endif /* VERSION_conduit */
#ifndef MIN_VERSION_conduit
#define MIN_VERSION_conduit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_conduit */

/* package conduit-extra-1.3.5 */
#ifndef VERSION_conduit_extra
#define VERSION_conduit_extra "1.3.5"
#endif /* VERSION_conduit_extra */
#ifndef MIN_VERSION_conduit_extra
#define MIN_VERSION_conduit_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_conduit_extra */

/* package cryptonite-0.29 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.29"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package memory-0.15.0 */
#ifndef VERSION_memory
#define VERSION_memory "0.15.0"
#endif /* VERSION_memory */
#ifndef MIN_VERSION_memory
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_memory */

/* package optparse-applicative-0.16.1.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.16.1.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 1)
#endif /* MIN_VERSION_optparse_applicative */

/* package optparse-generic-1.4.7 */
#ifndef VERSION_optparse_generic
#define VERSION_optparse_generic "1.4.7"
#endif /* VERSION_optparse_generic */
#ifndef MIN_VERSION_optparse_generic
#define MIN_VERSION_optparse_generic(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 7)
#endif /* MIN_VERSION_optparse_generic */

/* package process-1.6.13.2 */
#ifndef VERSION_process
#define VERSION_process "1.6.13.2"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 13)
#endif /* MIN_VERSION_process */

/* package random-1.2.0 */
#ifndef VERSION_random
#define VERSION_random "1.2.0"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package rio-0.1.21.0 */
#ifndef VERSION_rio
#define VERSION_rio "0.1.21.0"
#endif /* VERSION_rio */
#ifndef MIN_VERSION_rio
#define MIN_VERSION_rio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 21)
#endif /* MIN_VERSION_rio */

/* package system-filepath-0.4.14 */
#ifndef VERSION_system_filepath
#define VERSION_system_filepath "0.4.14"
#endif /* VERSION_system_filepath */
#ifndef MIN_VERSION_system_filepath
#define MIN_VERSION_system_filepath(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 14)
#endif /* MIN_VERSION_system_filepath */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package tuple-0.3.0.2 */
#ifndef VERSION_tuple
#define VERSION_tuple "0.3.0.2"
#endif /* VERSION_tuple */
#ifndef MIN_VERSION_tuple
#define MIN_VERSION_tuple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_tuple */

/* package unliftio-0.2.21.0 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.21.0"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 21)
#endif /* MIN_VERSION_unliftio */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* tool gcc-11.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  2 || \
  (major1) == 11 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.8.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "hcryptomotor-0.1.0.0-KcbFUg4nvw93jrQfKic6Rt-hcryptomotor-decrypt"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package aeson-1.5.6.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.5.6.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_aeson */

/* package aeson-pretty-0.8.9 */
#ifndef VERSION_aeson_pretty
#define VERSION_aeson_pretty "0.8.9"
#endif /* VERSION_aeson_pretty */
#ifndef MIN_VERSION_aeson_pretty
#define MIN_VERSION_aeson_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_aeson_pretty */

/* package attoparsec-0.13.2.5 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.13.2.5"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_attoparsec */

/* package attoparsec-binary-0.2 */
#ifndef VERSION_attoparsec_binary
#define VERSION_attoparsec_binary "0.2"
#endif /* VERSION_attoparsec_binary */
#ifndef MIN_VERSION_attoparsec_binary
#define MIN_VERSION_attoparsec_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_attoparsec_binary */

/* package base-4.14.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package conduit-1.3.4.2 */
#ifndef VERSION_conduit
#define VERSION_conduit "1.3.4.2"
#endif /* VERSION_conduit */
#ifndef MIN_VERSION_conduit
#define MIN_VERSION_conduit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_conduit */

/* package conduit-extra-1.3.5 */
#ifndef VERSION_conduit_extra
#define VERSION_conduit_extra "1.3.5"
#endif /* VERSION_conduit_extra */
#ifndef MIN_VERSION_conduit_extra
#define MIN_VERSION_conduit_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_conduit_extra */

/* package cryptonite-0.29 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.29"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package memory-0.15.0 */
#ifndef VERSION_memory
#define VERSION_memory "0.15.0"
#endif /* VERSION_memory */
#ifndef MIN_VERSION_memory
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_memory */

/* package optparse-applicative-0.16.1.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.16.1.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 1)
#endif /* MIN_VERSION_optparse_applicative */

/* package optparse-generic-1.4.7 */
#ifndef VERSION_optparse_generic
#define VERSION_optparse_generic "1.4.7"
#endif /* VERSION_optparse_generic */
#ifndef MIN_VERSION_optparse_generic
#define MIN_VERSION_optparse_generic(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 7)
#endif /* MIN_VERSION_optparse_generic */

/* package process-1.6.13.2 */
#ifndef VERSION_process
#define VERSION_process "1.6.13.2"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 13)
#endif /* MIN_VERSION_process */

/* package random-1.2.0 */
#ifndef VERSION_random
#define VERSION_random "1.2.0"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package rio-0.1.21.0 */
#ifndef VERSION_rio
#define VERSION_rio "0.1.21.0"
#endif /* VERSION_rio */
#ifndef MIN_VERSION_rio
#define MIN_VERSION_rio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 21)
#endif /* MIN_VERSION_rio */

/* package system-filepath-0.4.14 */
#ifndef VERSION_system_filepath
#define VERSION_system_filepath "0.4.14"
#endif /* VERSION_system_filepath */
#ifndef MIN_VERSION_system_filepath
#define MIN_VERSION_system_filepath(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 14)
#endif /* MIN_VERSION_system_filepath */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package tuple-0.3.0.2 */
#ifndef VERSION_tuple
#define VERSION_tuple "0.3.0.2"
#endif /* VERSION_tuple */
#ifndef MIN_VERSION_tuple
#define MIN_VERSION_tuple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_tuple */

/* package unliftio-0.2.21.0 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.21.0"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 21)
#endif /* MIN_VERSION_unliftio */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* tool gcc-11.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  2 || \
  (major1) == 11 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.8.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "hcryptomotor-0.1.0.0-1FT1lKMubG3Edf5pmCV6Xw-hcryptomotor-encrypt"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package aeson-1.5.6.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.5.6.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_aeson */

/* package aeson-pretty-0.8.9 */
#ifndef VERSION_aeson_pretty
#define VERSION_aeson_pretty "0.8.9"
#endif /* VERSION_aeson_pretty */
#ifndef MIN_VERSION_aeson_pretty
#define MIN_VERSION_aeson_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 9)
#endif /* MIN_VERSION_aeson_pretty */

/* package attoparsec-0.13.2.5 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.13.2.5"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_attoparsec */

/* package attoparsec-binary-0.2 */
#ifndef VERSION_attoparsec_binary
#define VERSION_attoparsec_binary "0.2"
#endif /* VERSION_attoparsec_binary */
#ifndef MIN_VERSION_attoparsec_binary
#define MIN_VERSION_attoparsec_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_attoparsec_binary */

/* package base-4.14.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package conduit-1.3.4.2 */
#ifndef VERSION_conduit
#define VERSION_conduit "1.3.4.2"
#endif /* VERSION_conduit */
#ifndef MIN_VERSION_conduit
#define MIN_VERSION_conduit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_conduit */

/* package conduit-extra-1.3.5 */
#ifndef VERSION_conduit_extra
#define VERSION_conduit_extra "1.3.5"
#endif /* VERSION_conduit_extra */
#ifndef MIN_VERSION_conduit_extra
#define MIN_VERSION_conduit_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_conduit_extra */

/* package cryptonite-0.29 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.29"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package memory-0.15.0 */
#ifndef VERSION_memory
#define VERSION_memory "0.15.0"
#endif /* VERSION_memory */
#ifndef MIN_VERSION_memory
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_memory */

/* package process-1.6.13.2 */
#ifndef VERSION_process
#define VERSION_process "1.6.13.2"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 13)
#endif /* MIN_VERSION_process */

/* package random-1.2.0 */
#ifndef VERSION_random
#define VERSION_random "1.2.0"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package rio-0.1.21.0 */
#ifndef VERSION_rio
#define VERSION_rio "0.1.21.0"
#endif /* VERSION_rio */
#ifndef MIN_VERSION_rio
#define MIN_VERSION_rio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 21)
#endif /* MIN_VERSION_rio */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package tuple-0.3.0.2 */
#ifndef VERSION_tuple
#define VERSION_tuple "0.3.0.2"
#endif /* VERSION_tuple */
#ifndef MIN_VERSION_tuple
#define MIN_VERSION_tuple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_tuple */

/* package unliftio-0.2.21.0 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.21.0"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 21)
#endif /* MIN_VERSION_unliftio */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* tool gcc-11.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  2 || \
  (major1) == 11 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.8.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "hcryptomotor-0.1.0.0-4IyfMB61G5A7BOaWvHbYiJ-hcryptomotor-genkey"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package attoparsec-0.13.2.5 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.13.2.5"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_attoparsec */

/* package attoparsec-binary-0.2 */
#ifndef VERSION_attoparsec_binary
#define VERSION_attoparsec_binary "0.2"
#endif /* VERSION_attoparsec_binary */
#ifndef MIN_VERSION_attoparsec_binary
#define MIN_VERSION_attoparsec_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_attoparsec_binary */

/* package base-4.14.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package conduit-1.3.4.2 */
#ifndef VERSION_conduit
#define VERSION_conduit "1.3.4.2"
#endif /* VERSION_conduit */
#ifndef MIN_VERSION_conduit
#define MIN_VERSION_conduit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_conduit */

/* package conduit-extra-1.3.5 */
#ifndef VERSION_conduit_extra
#define VERSION_conduit_extra "1.3.5"
#endif /* VERSION_conduit_extra */
#ifndef MIN_VERSION_conduit_extra
#define MIN_VERSION_conduit_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_conduit_extra */

/* package cryptonite-0.29 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.29"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package memory-0.15.0 */
#ifndef VERSION_memory
#define VERSION_memory "0.15.0"
#endif /* VERSION_memory */
#ifndef MIN_VERSION_memory
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_memory */

/* package options-1.2.1.1 */
#ifndef VERSION_options
#define VERSION_options "1.2.1.1"
#endif /* VERSION_options */
#ifndef MIN_VERSION_options
#define MIN_VERSION_options(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_options */

/* package process-1.6.13.2 */
#ifndef VERSION_process
#define VERSION_process "1.6.13.2"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 13)
#endif /* MIN_VERSION_process */

/* package random-1.2.0 */
#ifndef VERSION_random
#define VERSION_random "1.2.0"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package rio-0.1.21.0 */
#ifndef VERSION_rio
#define VERSION_rio "0.1.21.0"
#endif /* VERSION_rio */
#ifndef MIN_VERSION_rio
#define MIN_VERSION_rio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 21)
#endif /* MIN_VERSION_rio */

/* package system-filepath-0.4.14 */
#ifndef VERSION_system_filepath
#define VERSION_system_filepath "0.4.14"
#endif /* VERSION_system_filepath */
#ifndef MIN_VERSION_system_filepath
#define MIN_VERSION_system_filepath(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 14)
#endif /* MIN_VERSION_system_filepath */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package tuple-0.3.0.2 */
#ifndef VERSION_tuple
#define VERSION_tuple "0.3.0.2"
#endif /* VERSION_tuple */
#ifndef MIN_VERSION_tuple
#define MIN_VERSION_tuple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_tuple */

/* package unliftio-0.2.21.0 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.21.0"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 21)
#endif /* MIN_VERSION_unliftio */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* tool gcc-11.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  2 || \
  (major1) == 11 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.8.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "hcryptomotor-0.1.0.0-JMnJXk3LVn53OFjw47gtjK-hcryptomotor-sign"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package attoparsec-0.13.2.5 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.13.2.5"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_attoparsec */

/* package attoparsec-binary-0.2 */
#ifndef VERSION_attoparsec_binary
#define VERSION_attoparsec_binary "0.2"
#endif /* VERSION_attoparsec_binary */
#ifndef MIN_VERSION_attoparsec_binary
#define MIN_VERSION_attoparsec_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_attoparsec_binary */

/* package base-4.14.3.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.3.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package conduit-1.3.4.2 */
#ifndef VERSION_conduit
#define VERSION_conduit "1.3.4.2"
#endif /* VERSION_conduit */
#ifndef MIN_VERSION_conduit
#define MIN_VERSION_conduit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_conduit */

/* package conduit-extra-1.3.5 */
#ifndef VERSION_conduit_extra
#define VERSION_conduit_extra "1.3.5"
#endif /* VERSION_conduit_extra */
#ifndef MIN_VERSION_conduit_extra
#define MIN_VERSION_conduit_extra(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_conduit_extra */

/* package cryptonite-0.29 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.29"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */

/* package hcryptomotor-0.1.0.0 */
#ifndef VERSION_hcryptomotor
#define VERSION_hcryptomotor "0.1.0.0"
#endif /* VERSION_hcryptomotor */
#ifndef MIN_VERSION_hcryptomotor
#define MIN_VERSION_hcryptomotor(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_hcryptomotor */

/* package memory-0.15.0 */
#ifndef VERSION_memory
#define VERSION_memory "0.15.0"
#endif /* VERSION_memory */
#ifndef MIN_VERSION_memory
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_memory */

/* package options-1.2.1.1 */
#ifndef VERSION_options
#define VERSION_options "1.2.1.1"
#endif /* VERSION_options */
#ifndef MIN_VERSION_options
#define MIN_VERSION_options(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_options */

/* package process-1.6.13.2 */
#ifndef VERSION_process
#define VERSION_process "1.6.13.2"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 13)
#endif /* MIN_VERSION_process */

/* package random-1.2.0 */
#ifndef VERSION_random
#define VERSION_random "1.2.0"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package rio-0.1.21.0 */
#ifndef VERSION_rio
#define VERSION_rio "0.1.21.0"
#endif /* VERSION_rio */
#ifndef MIN_VERSION_rio
#define MIN_VERSION_rio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 21)
#endif /* MIN_VERSION_rio */

/* package system-filepath-0.4.14 */
#ifndef VERSION_system_filepath
#define VERSION_system_filepath "0.4.14"
#endif /* VERSION_system_filepath */
#ifndef MIN_VERSION_system_filepath
#define MIN_VERSION_system_filepath(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 14)
#endif /* MIN_VERSION_system_filepath */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package tuple-0.3.0.2 */
#ifndef VERSION_tuple
#define VERSION_tuple "0.3.0.2"
#endif /* VERSION_tuple */
#ifndef MIN_VERSION_tuple
#define MIN_VERSION_tuple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_tuple */

/* package unliftio-0.2.21.0 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.21.0"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 21)
#endif /* MIN_VERSION_unliftio */

/* package utf8-string-1.0.2 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.2"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_utf8_string */

/* tool gcc-11.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  2 || \
  (major1) == 11 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.7 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.7"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.7 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.7"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-1.8.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.7 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.7"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "hcryptomotor-0.1.0.0-6WzLvINLb7wIMPbHJFqJT1-hcryptomotor-verify"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
